version: '3'
services:
  neo4j:
    image: neo4j:5.20-community
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./docker/db/conf:/var/lib/neo4j/conf
      - ./docker/db/data:/data
      - ./docker/db/logs:/logs
      - ./docker/db/plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_AUTH=neo4j/changeme123
      - NEO4J_server_memory_pagecache_size=4G
      - NEO4J_dbms_memory_transaction_total_max=4G
      - NEO4J_dbms.memory_heap.initial_size=4G
      - NEO4J_server_memory_heap_max__size=16G
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    deploy:
      resources:
        reservations:
          cpus: '12'
          memory: 8G